from __future__ import annotations
from typing import Any, Protocol

class ProductServices(Protocol):
    def dashboard(self) -> dict[str, Any]: ...
    def list_jobs(self, filters: dict[str, Any]) -> dict[str, Any]: ...
    def get_job(self, job_id: str) -> dict[str, Any]: ...
    def set_review_status(self, job_id: str, status: str) -> dict[str, Any]: ...
    def create_package(self, job_id: str, cover_letter: bool = False, force: bool = False) -> dict[str, Any]: ...
    def get_package(self, package_id: str) -> dict[str, Any]: ...
    def approve_package(self, package_id: str) -> dict[str, Any]: ...
    def reject_package(self, package_id: str) -> dict[str, Any]: ...
    def list_applications(self) -> list[dict[str, Any]]: ...
    def transition_application(self, application_id: str, new_state: str, payload: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def launch_autofill(self, application_id: str) -> dict[str, Any]: ...
    def get_autofill(self, session_id: str) -> dict[str, Any]: ...
    def confirm_ready(self, session_id: str, confirmation: bool) -> dict[str, Any]: ...
    def mark_submitted_manually(self, session_id: str, confirmation: bool) -> dict[str, Any]: ...
    def list_resume_facts(self) -> dict[str, Any]: ...
    def import_resume(self, filename: str, content: bytes) -> dict[str, Any]: ...
    def get_resume_import(self, import_id: str) -> dict[str, Any]: ...
    def approve_resume_fact(self, fact_id: str, import_id: str) -> dict[str, Any]: ...
    def reject_resume_fact(self, fact_id: str, import_id: str) -> dict[str, Any]: ...
    def reassess_immigration(self, job_id: str) -> dict[str, Any]: ...
    def immigration_overview(self) -> dict[str, Any]: ...
    def settings_summary(self) -> dict[str, Any]: ...
